# Site settings
title: Joel Kalete 
description: Joel Kalete's Portfolio
favicon: /assets/img/avatar.JPG
baseurl: https://joelkay.github.io
url: https://joelkay.github.io
rss_url: /pages/atom.xml
google_analytics: 

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Joel Kalete
  title: Aspiring Developer
  address: Kent, United Kingdom
  email: joeldkay01@gmail.com
  link: http://joelkalete.com
  weibo:
  github: joelkay
  linkedin: joelkalete
  twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Publisure
      location: Kent, United Kingdom
      title: Application Support
      started: 2016
      duration: (2016 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Edgar&Co
      location: London, United Kingdom
      title: Consultant
      started: 2012
      duration: (2012 - present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: University of Kent
      location: Kent, United Kingdom
      degree: Bachelor
      major: Computer Science
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Luganda
      proficiency: Proficient
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: MySQL
      percentage: 90%
    - skill3:
      name: C#
      percentage: 50%
    - skill4:
      name: PHP
      percentage: 40%
    - skill5:
      name: Python
      percentage: 40%
